#!/usr/bin/env bash
#
# DO NOT EDIT THIS FILE! IF YOU WANT TO CHANGE SOMETHING, DO IT IN THE SCRIPTS
# OR PROCESSORS.

# Load SHE abilities. No need to reload in the scripts.
source <(curl -fsSL https://she.alaturka.io/source) -boot

set -euo pipefail; [[ -z ${TRACE:-} ]] || set -x

export DEBIAN_FRONTEND=noninteractive

enter ../lib/processors; run pre;     leave
enter ../lib/scripts;    run scripts; leave
enter ../lib/processors; run post;    leave
